name: Auto-merge Dependencies

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]' || github.actor == 'dependabot[bot]'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build and test
      run: |
        docker build -t schedule-manager:test .
        docker run -d -p 6247:6247 --name test-container schedule-manager:test
        sleep 15
        
    - name: Comprehensive health check
      run: |
        # Basic health check
        curl -f http://localhost:6247/health
        
        # Verify health response structure and data
        HEALTH_RESPONSE=$(curl -s http://localhost:6247/health)
        echo "Health response: $HEALTH_RESPONSE"
        
        # Validate JSON structure
        echo "$HEALTH_RESPONSE" | jq -e 'type == "object"'
        echo "$HEALTH_RESPONSE" | jq -e 'has("status") and has("timestamp") and has("checks") and has("version")'
        
        # Check if all systems are healthy
        echo "$HEALTH_RESPONSE" | jq -e '.status == "healthy"'
        echo "$HEALTH_RESPONSE" | jq -e '.checks.storage.status == "healthy"'
        echo "$HEALTH_RESPONSE" | jq -e '.checks.auth.status == "healthy"'
        echo "$HEALTH_RESPONSE" | jq -e '.checks.calendar.status == "healthy"'
        
        # Validate timestamp is recent (within last 60 seconds)
        TIMESTAMP=$(echo "$HEALTH_RESPONSE" | jq -r '.timestamp')
        CURRENT_TIME=$(date +%s)
        TIME_DIFF=$((CURRENT_TIME - ${TIMESTAMP%.*}))
        if [ $TIME_DIFF -gt 60 ]; then
          echo "Health check timestamp too old: $TIME_DIFF seconds"
          exit 1
        fi
        
        # Validate version exists
        echo "$HEALTH_RESPONSE" | jq -e '.version != null and .version != ""'
        
    - name: Test core functionality
      run: |
        # Test login page loads
        curl -f http://localhost:6247/login
        
        # Test calendar generation
        curl -f http://localhost:6247/calendar.ics
        
        # Test individual engineer calendar
        curl -f http://localhost:6247/engineer/alex.ics
        
    - name: Cleanup
      run: docker stop test-container
      
    - name: Auto-merge
      if: success()
      uses: pascalgn/automerge-action@v0.16.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        merge_method: squash
        merge_commit_message: "chore: auto-merge dependency update"
