name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8 mypy
        
    - name: Run Black
      run: black --check app/
      
    - name: Run isort
      run: isort --check-only app/
      
    - name: Run Flake8
      run: flake8 app/
      
    - name: Run MyPy
      run: mypy app/ --ignore-missing-imports

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker images
      run: docker-compose -f docker-compose.test.yml build
      
    - name: Start containers
      run: docker-compose -f docker-compose.test.yml up -d
      
    - name: Health check
      run: |
        sleep 10
        curl -f http://localhost:6247/health || exit 1
        curl -f http://localhost:6248/health || exit 1
        
    - name: Stop containers
      run: docker-compose -f docker-compose.test.yml down