name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8
        
    - name: Run Black
      run: black --check app/
      
    - name: Run isort
      run: isort --check-only app/
      
    - name: Run Flake8
      run: flake8 app/
      

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t schedule-manager:test .
      
    - name: Run container
      run: docker run -d -p 6247:6247 --name test-container schedule-manager:test
      
    - name: Wait for startup
      run: sleep 15
      
    - name: Health check
      run: curl -f http://localhost:6247/health
      
    - name: Stop container
      run: docker stop test-container