name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8
        
    - name: Run Black
      run: black --check app/
      
    - name: Run isort
      run: isort --check-only app/
      
    - name: Run Flake8
      run: flake8 app/
      

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t schedule-manager:test .
      
    - name: Run container
      run: docker run -d -p 6247:6247 --name test-container schedule-manager:test
      
    - name: Wait for startup
      run: sleep 15
      
    - name: Comprehensive health check
      run: |
        # Basic health check
        curl -f http://localhost:6247/health
        
        # Verify health response structure and data
        HEALTH_RESPONSE=$(curl -s http://localhost:6247/health)
        echo "Health response: $HEALTH_RESPONSE"
        
        # Validate JSON structure
        echo "$HEALTH_RESPONSE" | jq -e 'type == "object"'
        echo "$HEALTH_RESPONSE" | jq -e 'has("status") and has("timestamp") and has("checks") and has("version")'
        
        # Check if all systems are healthy
        echo "$HEALTH_RESPONSE" | jq -e '.status == "healthy"'
        echo "$HEALTH_RESPONSE" | jq -e '.checks.storage.status == "healthy"'
        echo "$HEALTH_RESPONSE" | jq -e '.checks.auth.status == "healthy"'
        echo "$HEALTH_RESPONSE" | jq -e '.checks.calendar.status == "healthy"'
        
        # Validate timestamp is recent (within last 60 seconds)
        TIMESTAMP=$(echo "$HEALTH_RESPONSE" | jq -r '.timestamp')
        CURRENT_TIME=$(date +%s)
        TIME_DIFF=$((CURRENT_TIME - ${TIMESTAMP%.*}))
        if [ $TIME_DIFF -gt 60 ]; then
          echo "Health check timestamp too old: $TIME_DIFF seconds"
          exit 1
        fi
        
        # Validate version exists
        echo "$HEALTH_RESPONSE" | jq -e '.version != null and .version != ""'
        
    - name: Test core functionality
      run: |
        # Test login page loads
        curl -f http://localhost:6247/login
        
        # Test calendar generation
        curl -f http://localhost:6247/calendar.ics
        
        # Test individual engineer calendar
        curl -f http://localhost:6247/engineer/alex.ics
      
    - name: Stop container
      run: docker stop test-container